kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: readonly
rules:
  - apiGroups: [""]
    resources: [
        "bindings", "componentstatuses", "configmaps", "endpoints", "events",
        "limitranges", "namespaces", "namespaces/finalize", "namespaces/status",
        "nodes", "nodes/proxy", "nodes/status",
        "persistentvolumeclaims", "persistentvolumeclaims/status", "persistentvolumes",
        "pods", "replicationcontrollers", "resourcequotas", "resourcequotas/status",
        "serviceaccounts", "services"
    ]
    verbs: ["get", "list", "watch", "proxy", "redirect"]
    nonResourceURLs: []

  - apiGroups: ["apps", "batch", "autoscaling", "policy"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "proxy", "redirect"]
    nonResourceURLs: []

  - apiGroups: ["extensions"]
    resources: [
        "daemonsets", "deployments", "horizontalpodautoscalers", "ingress",
        "jobs", "replicasets", "replicationcontrollers",
        "networkpolicies",

        "daemonsets/status",
        "deployments/rollback",
        "deployments/scale",
        "deployments/status",
        "horizontalpodautoscalers/status",
        "ingresses/status",
        "jobs/status",
        "replicasets/scale",
        "replicasets/status",
        "replicationcontrollers/scale"
    ]
    verbs: ["get", "list", "watch", "proxy", "redirect"]
    nonResourceURLs: []
