apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
data:
  aggregator-ca.crt: ${aggregator_ca_cert}
  apiserver.key: ${apiserver_key}
  apiserver.crt: ${apiserver_cert}
  apiserver-proxy.key: ${apiserver_proxy_key}
  apiserver-proxy.crt: ${apiserver_proxy_cert}
  service-account.pub: ${serviceaccount_pub}
  ca.crt: ${kube_ca_cert}
  etcd-client-ca.crt: ${etcd_ca_cert}
  etcd-client.crt: ${etcd_client_cert}
  etcd-client.key: ${etcd_client_key}
  oidc-ca.crt: ${oidc_ca_cert}
