apiVersion: v1
kind: Service
metadata:
  name: tectonic-openldap
  namespace: tectonic-system
  labels:
    app: tectonic-openldap
spec:
  ports:
  - port: 389
    protocol: TCP
  selector:
    app: tectonic-openldap
  type: NodePort
