kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-openldap
  namespace: tectonic-system
data:
    ldap.ldif: |
      dn: cn=john,dc=example,dc=org
      objectClass: person
      objectClass: inetOrgPerson
      uid: john.doe
      mail: john.doe@example.org
      cn: john
      sn: doe
      userPassword:: e1NTSEF9dkltSFZkNTgzN3JBaVdEZ2xyVXFyeE9nM1FETHBkM04=

      dn: cn=jane,dc=example,dc=org
      objectClass: person
      objectClass: inetOrgPerson
      uid: jane.doe
      mail: jane.doe@example.org
      cn: jane
      sn: doe
      userPassword:: e1NTSEF9dkltSFZkNTgzN3JBaVdEZ2xyVXFyeE9nM1FETHBkM04=

      dn: ou=groups,dc=example,dc=org
      ou: groups
      objectClass: top
      objectClass: organizationalUnit

      dn: cn=tstgrp,ou=groups,dc=example,dc=org
      objectClass: top
      objectClass: groupOfNames
      member: cn=john,dc=example,dc=org
      cn: tstgrp
    # script to perform the ldapadd
    add-users.sh: |
      #!/bin/sh
      while :
      do
        ldapadd -x -D "cn=admin,dc=example,dc=org" -w admin -f /tmp/ldap.ldif -h localhost -p 389
        if [ "$?" -eq "0" ]; then
         echo "LDAP server populated"
         sleep infinity
        fi
        sleep 1
      done
