apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-openldap
  namespace: tectonic-system
  labels:
    app: tectonic-openldap
spec:
  replicas: 1
  template:
    metadata:
      name: tectonic-openldap
      labels:
        app: tectonic-openldap
    spec:
      volumes:
      - name: ldap-ldif
        configMap:
          name: tectonic-openldap
          items:
          - key: ldap.ldif
            path: ldap.ldif
      - name: ldap-script
        configMap:
          name: tectonic-openldap
          items:
          - key: add-users.sh
            path: add-users.sh
      containers:
      - name: tectonic-openldap-serv
        image: osixia/openldap:1.1.6
        ports:
        - containerPort: 389
          name: openldap
      - name: tectonic-openldap-exec
        image: osixia/openldap:1.1.6
        command: ["/bin/bash", "/tmp/scripts/add-users.sh"]
        volumeMounts:
        - mountPath: /tmp
          name: ldap-ldif
        - mountPath: /tmp/scripts
          name: ldap-script
      imagePullSecrets:
      - name: coreos-pull-secret
