apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: container-linux-update-operator
  name: container-linux-update-operator
  namespace: tectonic-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: container-linux-update-operator
      name: container-linux-update-operator
    spec:
      containers:
      - name: update-operator
        image: quay.io/coreos/container-linux-update-operator:v0.2.0
        command:
        - "/bin/update-operator"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
