kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: tectonic-admin-user
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tectonic-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
