apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-version-operator
  namespace: tectonic-system
  labels:
    k8s-app: kube-version-operator
    managed-by-channel-operator: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-version-operator
  template:
    metadata:
      labels:
        k8s-app: kube-version-operator
        tectonic-app-version-name: kubernetes
    spec:
      containers:
      - name: kube-version-operator
        image: quay.io/coreos/kube-version-operator:32d089ced0064ccdc2b46691d90041c3b3a5b4f7
      imagePullSecrets:
      - name: coreos-pull-secret
