apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: tectonic-system
  labels:
    k8s-app: node-agent
spec:
  template:
    metadata:
      labels:
        k8s-app: node-agent
    spec:
      containers:
      - name: node-agent
        image: quay.io/coreos/node-agent:96db3df24c2ddf0b82c38111c71179c5b10de0c9
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: systemd
          mountPath: /etc/systemd/system
        - name: dbus
          mountPath: /var/run/dbus
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
      imagePullSecrets:
      - name: coreos-pull-secret
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: systemd
        hostPath:
          path: /etc/systemd/system
      - name: dbus
        hostPath:
          path: /var/run/dbus
