apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-channel-operator
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-channel-operator
    managed-by-channel-operator: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tectonic-channel-operator
  template:
    metadata:
      labels:
        k8s-app: tectonic-channel-operator
        tectonic-app-version-name: tectonic-cluster
    spec:
      containers:
      - name: tectonic-channel-operator
        image: quay.io/coreos/tectonic-channel-operator:c0287c3ca5960d5f557f98ed86b3f64260d95e7c
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: tectonic-config
                key: clusterID
        volumeMounts:
        - name: certs
          mountPath: /etc/ssl/certs
      imagePullSecrets:
      - name: coreos-pull-secret
      volumes:
      - name: certs
        hostPath:
          path: /usr/share/ca-certificates
