apiVersion: "extensions/v1beta1"
kind: "ThirdPartyResource"
metadata:
  name: "app-version.coreos.com"
description: "An experimental specification for Tectonic components' versions"
versions:
  - name: "v1"