apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: tectonic-system
  labels:
    k8s-app: node-agent
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: node-agent
    spec:
      containers:
      - name: node-agent
        image: ${node_agent_image}
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: systemd
          mountPath: /etc/systemd/system
        - name: var-run
          mountPath: /var/run
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
      imagePullSecrets:
      - name: coreos-pull-secret
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: systemd
        hostPath:
          path: /etc/systemd/system
      - name: var-run
        hostPath:
          path: /var/run
