apiVersion: v1
kind: ConfigMap
metadata:
  name: tectonic-monitoring
  namespace: tectonic-system
data:
  config.yaml: |+
    prometheusOperator:
      baseImage: ${replace(prometheus_operator_image,image_re,"$1")}
      prometheusConfigReloaderBaseImage: ${replace(prometheus_config_reload_image,image_re,"$1")}
      configReloaderBaseImage: ${replace(config_reload_image,image_re,"$1")}
    prometheusK8s:
      baseImage: ${replace(prometheus_image,image_re,"$1")}
    alertmanagerMain:
      baseImage: ${replace(alertmanager_image,image_re,"$1")}
    ingress:
      baseAddress: ${console_base_address}
    auth:
      baseImage: ${replace(tectonic_monitoring_auth_image,image_re,"$1")}
    nodeExporter:
      baseImage: ${replace(node_exporter_image,image_re,"$1")}
    kubeStateMetrics:
      baseImage: ${replace(kube_state_metrics_image,image_re,"$1")}
