apiVersion: v1
kind: ConfigMap
metadata:
  name: tectonic-monitoring
  namespace: tectonic-system
data:
  config.yaml: |+
    prometheusOperator:
      baseImage: ${replace(prometheus_operator_image,image_re,"$1")}
      prometheusConfigReloaderBaseImage: ${replace(prometheus_config_reload_image,image_re,"$1")}
      configReloaderBaseImage: ${replace(config_reload_image,image_re,"$1")}
    prometheusK8s:
      baseImage: ${replace(prometheus_image,image_re,"$1")}
      resources: 
        limits: 
          cpu: ${prometheus_limit_cpu}
          memory: ${prometheus_limit_mem}
        requests:
          cpu: ${prometheus_request_cpu}
          memory: ${prometheus_request_mem}
    alertmanagerMain:
      baseImage: ${replace(alertmanager_image,image_re,"$1")}
    ingress:
      baseAddress: ${console_base_address}
