apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: tectonic-ingress
data:
  ingress-config: |
    apiVersion: v1
    kind: TectonicIngressOperatorConfig
    installerPlatform: ${platform}
