apiVersion: v1
kind: Service
metadata:
  name: tectonic-identity
  namespace: tectonic-system
  labels:
    app: tectonic-identity
    component: identity
spec:
  selector:
    app: tectonic-identity
    component: identity
  ports:
  - name: worker
    protocol: TCP
    port: 5556
