apiVersion: v1
kind: Service
metadata:
  name: tectonic-identity-api
  namespace: tectonic-system
spec:
  selector:
    app: tectonic-identity
    component: identity
  ports:
  - name: api
    protocol: TCP
    port: 5557
