apiVersion: v1
kind: Service
metadata:
  name: tectonic-identity
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-identity
    component: identity
spec:
  selector:
    k8s-app: tectonic-identity
    component: identity
  ports:
  - name: worker
    protocol: TCP
    port: 5556
---
apiVersion: v1
kind: Service
metadata:
  name: tectonic-identity-api
  namespace: tectonic-system
spec:
  selector:
    k8s-app: tectonic-identity
    component: identity
  ports:
  - name: api
    protocol: TCP
    port: 5557
