apiVersion: v1
kind: ConfigMap
metadata:
    name: addon-config
    namespace: kube-system
data:
    addon-config: 
        apiVersion: v1
        kind: addonConfig
        heapsterConfig: 
        dnsConfig:
            clusterIP: ${kube_dns_service_ip}
