kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-config
  namespace: tectonic-system
data:
  clusterID: "${cluster_id}"
  installerPlatform: "${platform}"
  certificatesStrategy: "${certificates_strategy}"
  tectonicUpdaterEnabled: "true"
  consoleBaseAddress: "${console_base_address}"
  kubeAPIServerURL: "${kube_apiserver_url}"
  tectonicVersion: "${tectonic_version}"
