apiVersion: v1
kind: Service
metadata:
  name: hellogo
spec:
  type: LoadBalancer
  selector:
    name: hellogo
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
