apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs1
  labels:
    kind: ebs
    failure-domain.beta.kubernetes.io/region: ( VOLUME REGION )
    failure-domain.beta.kubernetes.io/zone: ( VOLUME ZONE )
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: ( VOLUME ID )
    fsType: ext4
