kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      kind: "ebs"
