kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: ingress-controller
rules:
  - apiGroups:
    - extensions
    - ""
    resources:
    - configmaps
    - ingresses
    - endpoints
    - services
    - secrets
    - pods
    verbs: 
    - get
    - watch
    - list
    nonResourceURLs: []
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    nonResourceURLs: []
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    nonResourceURLs: []