apiVersion: v1
kind: Secret
metadata:
  name: tectonic-identity-grpc-server-secret
  namespace: tectonic-system
type: Opaque
data:
  server-cert: ${identity_server_tls_cert}
  server-key: ${identity_server_tls_key}
  ca-cert: ${ca_cert}
