apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
spec:
  selector:
    k8s-app: heapster
  ports:
    - port: 80
      targetPort: 8082