apiVersion: v1
kind: Secret
metadata:
  name: etcd-operator-client-tls
  namespace: kube-system
type: Opaque
data:
  etcd-ca-crt.pem: ${etcd_ca_cert}
  etcd-crt.pem: ${etcd_client_cert}
  etcd-key.pem: ${etcd_client_key}
