apiVersion: v1
kind: Secret
metadata:
  name: etcd-member-client-tls
  namespace: kube-system
type: Opaque
data:
  client-ca-crt.pem: ${etcd_ca_cert}
  client-crt.pem: ${etcd_client_cert}
  client-key.pem: ${etcd_client_key}
