apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: etcd-operator
  name: etcd-operator
  namespace: tectonic-system
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: etcd-operator
    spec:
      containers:
        - env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOME
              value: /tmp
          image: ${etcd_operator_image}
          name: etcd-operator
      nodeSelector:
        node-role.kubernetes.io/node: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
