apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-scheduler
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: control-plane
        component: kube-scheduler
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: kube-scheduler
        image: ${hyperkube_image}
        command:
        - ./hyperkube
        - scheduler
        - --leader-elect=true
