apiVersion: v1
kind: Secret
metadata:
  name: openshift-apiserver
  namespace: kube-system
type: Opaque
data:
  aggregator-ca.crt: ${aggregator_ca_cert}
  aggregator-ca.key: ${aggregator_ca_key}
  apiserver.key: ${apiserver_key}
  apiserver.crt: ${apiserver_cert}
  openshift-apiserver.key: ${openshift_apiserver_key}
  openshift-apiserver.crt: ${openshift_apiserver_cert}
  apiserver-proxy.key: ${apiserver_proxy_key}
  apiserver-proxy.crt: ${apiserver_proxy_cert}
  service-account.pub: ${serviceaccount_pub}
  service-account.key: ${serviceaccount_key}
  root-ca.crt: ${root_ca_cert}
  kube-ca.crt: ${kube_ca_cert}
  etcd-client-ca.crt: ${etcd_ca_cert}
  etcd-client.crt: ${etcd_client_cert}
  etcd-client.key: ${etcd_client_key}
  oidc-ca.crt: ${oidc_ca_cert}
  service-serving-ca.crt: ${service_serving_ca_cert}
  service-serving-ca.key: ${service_serving_ca_key}
  kubeconfig: ${openshift_loopback_kubeconfig}
  
