apiVersion: coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-cluo-operator
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
spec:
  desiredVersion: ${tectonic_cluo_operator_version}
  paused: false
