apiVersion: v1
kind: Service
metadata:
  # keep it under 24 chars
  name: tectonic-lb
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-lb
    component: ingress-controller
spec:
  type: ClusterIP
  selector:
    k8s-app: tectonic-lb
    component: ingress-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
