apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: fluentd
  namespace: logging
  labels:
    prometheus: fluentd
    component: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus-fluentd
  serviceMonitorSelector:
    matchLabels:
      app: fluentd
  resources:
    requests:
      memory: 250Mi
