apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: tectonic-system
  labels:
    k8s-app: alertmanager
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiAxMmgKICByb3V0ZXM6CiAgLSBtYXRjaDoKICAgICAgYWxlcnRuYW1lOiBEZWFkTWFuc1N3aXRjaAogICAgcmVwZWF0X2ludGVydmFsOiA1bQogICAgcmVjZWl2ZXI6IGRlYWRtYW5zc3dpdGNoCnJlY2VpdmVyczoKLSBuYW1lOiBkZWFkbWFuc3N3aXRjaAo=
