apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: tectonic-system
  labels:
    k8s-app: alertmanager
    alertmanager: main
spec:
  replicas: 2
  baseImage: ${replace(alertmanager_image,image_re,"$1")}
  version: ${alertmanager_version}
  externalUrl: ${prometheus_external_url}
  resources:
    requests:
      memory: 40Mi
