apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: tectonic-system
  labels:
    k8s-app: alertmanager
spec:
  selector:
    matchLabels:
      k8s-app: alertmanager
      alertmanager: main
  namespaceSelector:
    matchNames:
    - tectonic-system
  endpoints:
  - port: web
    interval: 30s
