apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  namespace: tectonic-system
  labels:
    k8s-app: prometheus
    prometheus: k8s
spec:
  replicas: 1
  baseImage: ${replace(prometheus_image,image_re,"$1")}
  version: ${prometheus_version}
  externalUrl: ${prometheus_external_url}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  alerting:
    alertmanagers:
    - namespace: tectonic-system
      name: alertmanager-main
      port: web
  resources:
    limits:
      cpu: ${prometheus_limit_cpu}
      memory: ${prometheus_limit_mem}
    requests:
      cpu: ${prometheus_request_cpu}
      memory: ${prometheus_request_mem}
