apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: tectonic-system
  labels:
    k8s-apps: http
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    interval: 15s
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames: 
    - kube-system
