apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: tectonic-system
  labels:
    k8s-app: prometheus
    prometheus: k8s
    name: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
    prometheus: k8s
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    protocol: TCP
