apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    k8s-app: etcd-operator
  name: etcd-operator
  namespace: kube-system
spec: 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template: 
    metadata: 
      labels: 
        k8s-app: etcd-operator
    spec:
      volumes:
      - name: debug-volume
        hostPath:
          path: /var/tmp
      containers: 
        - env: 
            - name: MY_POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: HOME
              value: /tmp
          image: ${etcd_operator_image}
          name: etcd-operator
          command:
          - /usr/local/bin/etcd-operator
          - --debug-logfile-path=/var/tmp/etcd-operator/debug/debug.log
          volumeMounts:
          - mountPath: /var/tmp/etcd-operator/debug
            name: debug-volume
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
