apiVersion: v1
kind: Service
metadata: 
  name: etcd-service
  namespace: kube-system
spec: 
  clusterIP: ${etcd_service_ip}
  ports: 
    - name: client
      port: 2379
      protocol: TCP
  selector: 
    app: etcd
    etcd_cluster: kube-etcd
