apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-tls
  namespace: kube-system
type: Opaque
data:
  etcd-client-ca.crt: ${etcd_ca_cert}
  etcd-client.crt: ${etcd_client_cert}
  etcd-client.key: ${etcd_client_key}
