# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-autoscaling'
gem 'aws-sdk-ec2'
gem 'aws-sdk-iam'
gem 'azure-storage-blob'
gem 'certificate_authority'
gem 'faker', '~>1.8.4'
gem 'net-ssh', '~>4.2.0'
gem 'rspec', '~>3.0'
gem 'rspec_tap'
gem 'rubocop', '~>0.49.1'
